### ISSUE TITLE
已经更新到5.3.1啦，大神，更新下啦

### ISSUE THREAD

**Issue by star8618** [Plutonium141/mosdns-config#5]
已经更新到5.3.1啦，大神，更新下啦

**Comment by Plutonium141** [comment]
v5不能用geosite和geoip了，单独弄域名列表有点麻烦，配置也看的我一头雾水，就一直没弄

**Comment by star8618** [comment]
include: []
log:
    file: /etc/mosdns/mosdns.log
    level: info
plugins:
    - args:
        files:
            - /etc/mosdns/rule/geosite_cn.txt
      tag: geosite_cn
      type: domain_set
    - args:
        files:
            - /etc/mosdns/rule/geoip-only-cn-private_cn.txt
      tag: geoip_cn
      type: ip_set
    - args:
        files:
            - /etc/mosdns/rule/geosite_apple.txt
      tag: geosite_apple
      type: domain_set
    - args:
        files:
            - /etc/mosdns/rule/geosite_geolocation-!cn.txt
      tag: geosite_no_cn
      type: domain_set
    - args:
        files:
            - /etc/mosdns/rule/whitelist.txt
      tag: whitelist
      type: domain_set
    - args:
        files:
            - /etc/mosdns/rule/blocklist.txt
      tag: blocklist
      type: domain_set
    - args:
        files:
            - /etc/mosdns/rule/greylist.txt
      tag: greylist
      type: domain_set
    - args:
        files:
            - /etc/mosdns/rule/ddnslist.txt
      tag: ddnslist
      type: domain_set
    - args:
        files:
            - /etc/mosdns/rule/hosts.txt
      tag: hosts
      type: hosts
    - args:
        files:
            - /etc/mosdns/rule/redirect.txt
      tag: redirect
      type: redirect
    - args:
        files:
            - /etc/mosdns/rule/disable-ads.txt
      tag: adlist
      type: domain_set
    - args:
        files:
            - /etc/mosdns/rule/local-ptr.txt
      tag: local_ptr
      type: domain_set
    - args:
        files:
            - /etc/mosdns/rule/cloudflare-cidr.txt
      tag: cloudflare_cidr
      type: ip_set
    - args:
        dump_file: /etc/mosdns/cache.dump
        dump_interval: 3600
        lazy_cache_ttl: 21600
        size: 55462
      tag: lazy_cache
      type: cache
    - args:
        concurrent: 2
        upstreams:
            - addr: 223.5.5.5
            - addr: 223.6.6.6
      tag: forward_alidns_udp
      type: forward
    - args:
        concurrent: 2
        upstreams:
            - addr: https://223.5.5.5/dns-query
              bootstrap: 127.0.0.1
              enable_pipeline: true
              idle_timeout: 30
              insecure_skip_verify: false
            - addr: https://223.6.6.6/dns-query
              bootstrap: 127.0.0.1
              enable_pipeline: true
              idle_timeout: 30
              insecure_skip_verify: false
      tag: forward_local
      type: forward
    - args:
        concurrent: 2
        upstreams:
            - addr: https://1.1.1.1/dns-query
              bootstrap: 127.0.0.1
              enable_pipeline: true
              idle_timeout: 30
              insecure_skip_verify: false
            - addr: https://1.0.0.1/dns-query
              bootstrap: 127.0.0.1
              enable_pipeline: true
              idle_timeout: 30
              insecure_skip_verify: false
      tag: forward_remote
      type: forward
    - args:
        - exec: prefer_ipv4
        - exec: ecs 110.34.181.1
        - exec: $forward_remote
      tag: forward_remote_upstream
      type: sequence
    - args:
        - exec: ttl 600-86400
      tag: modify_ttl
      type: sequence
    - args:
        - exec: ttl 5-5
      tag: modify_ddns_ttl
      type: sequence
    - args:
        - exec: $modify_ddns_ttl
          matches: qname $ddnslist
        - exec: $modify_ttl
          matches: '!qname $ddnslist'
        - exec: accept
          matches: has_resp
      tag: has_resp_sequence
      type: sequence
    - args:
        - exec: $forward_local
        - exec: drop_resp
          matches: '!resp_ip $geoip_cn'
      tag: query_is_non_local_ip
      type: sequence
    - args:
        always_standby: true
        primary: forward_remote_upstream
        secondary: forward_remote_upstream
        threshold: 500
      tag: fallback
      type: fallback
    - args:
        always_standby: true
        primary: query_is_non_local_ip
        secondary: forward_alidns_udp
        threshold: 100
      tag: apple_domain_fallback
      type: fallback
    - args:
        - exec: return
          matches: '!qname $geosite_apple'
        - exec: $apple_domain_fallback
      tag: query_is_apple_domain
      type: sequence
    - args:
        - exec: $forward_local
          matches: qname $ddnslist
      tag: query_is_ddns_domain
      type: sequence
    - args:
        - exec: $forward_local
          matches: qname $geosite_cn
      tag: query_is_local_domain
      type: sequence
    - args:
        - exec: $forward_remote_upstream
          matches: qname $geosite_no_cn
      tag: query_is_no_local_domain
      type: sequence
    - args:
        - exec: $forward_local
          matches: qname $whitelist
      tag: query_is_whitelist_domain
      type: sequence
    - args:
        - exec: $forward_remote_upstream
          matches: qname $greylist
      tag: query_is_greylist_domain
      type: sequence
    - args:
        - exec: reject 3
          matches: qname $blocklist
        - exec: reject 3
          matches: qname $adlist
        - exec: reject 3
          matches:
            - qtype 12
            - qname $local_ptr
        - exec: reject 3
          matches: qtype 65
      tag: query_is_reject_domain
      type: sequence
    - args:
        - exec: $hosts
        - exec: jump has_resp_sequence
        - exec: $lazy_cache
          matches:
            - '!qname $ddnslist'
            - '!qname $blocklist'
            - '!qname $adlist'
            - '!qname $local_ptr'
        - exec: $redirect
        - exec: jump has_resp_sequence
        - exec: $query_is_apple_domain
        - exec: jump has_resp_sequence
        - exec: $query_is_ddns_domain
        - exec: jump has_resp_sequence
        - exec: $query_is_whitelist_domain
        - exec: jump has_resp_sequence
        - exec: $query_is_reject_domain
        - exec: jump has_resp_sequence
        - exec: $query_is_greylist_domain
        - exec: jump has_resp_sequence
        - exec: $query_is_local_domain
        - exec: jump has_resp_sequence
        - exec: $query_is_no_local_domain
        - exec: jump has_resp_sequence
        - exec: $fallback
      tag: main_sequence
      type: sequence
    - args:
        entry: main_sequence
        listen: :53
      tag: udp_server
      type: udp_server
    - args:
        entry: main_sequence
        listen: :53
      tag: tcp_server
      type: tcp_server

**Comment by wenpo1975** [comment]
> v5不能用geosite和geoip了，单独弄域名列表有点麻烦，配置也看的我一头雾水，就一直没弄

可以的，这个是luci-app-mosdns v5.3的配置文件导出的，参考一下。

```
log:
  level: info
  file: "/var/log/mosdns.log"

# API 入口设置
api:
  http: "0.0.0.0:9091"

include: []

plugins:
  # 国内域名
  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_cn.txt"

  # 国内 IP
  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - "/var/mosdns/geoip_cn.txt"

  # 国外域名
  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_geolocation-!cn.txt"

  # 缓存
  - tag: lazy_cache
    type: cache
    args:
      size: 20000
      lazy_cache_ttl: 86400
      dump_file: "/etc/mosdns/cache.dump"
      dump_interval: 600

  # 转发至本地服务器
  - tag: forward_local
    type: forward
    args:
      upstreams:
        - addr: "https://doh.pub/dns-query"
          bootstrap: 180.76.76.76
        - addr: 119.29.29.29

  # 转发至远程服务器
  - tag: forward_remote
    type: forward
    args:
      upstreams:
        - addr: tls://8.8.8.8
          enable_pipeline: false

  # 国内解析
  - tag: local_sequence
    type: sequence
    args:
      - exec: $forward_local

  # 国外解析
  - tag: remote_sequence
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $forward_remote

  # 有响应终止返回
  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: has_resp
        exec: accept

  # fallback 用本地服务器 sequence
  # 返回非国内 ip 则 drop_resp
  - tag: query_is_local_ip
    type: sequence
    args:
      - exec: $local_sequence
      - matches: "!resp_ip $geoip_cn"
        exec: drop_resp

  # fallback 用远程服务器 sequence
  - tag: query_is_remote
    type: sequence
    args:
      - exec: $remote_sequence

  # fallback 用远程服务器 sequence
  - tag: fallback
    type: fallback
    args:
      primary: query_is_local_ip
      secondary: query_is_remote
      threshold: 500
      always_standby: true

  # 查询国内域名
  - tag: query_is_local_domain
    type: sequence
    args:
      - matches: qname $geosite_cn
        exec: $local_sequence

  # 查询国外域名
  - tag: query_is_no_local_domain
    type: sequence
    args:
      - matches: qname $geosite_no_cn
        exec: $remote_sequence

  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      - exec: $lazy_cache
      - exec: $query_is_local_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_no_local_domain
      - exec: jump has_resp_sequence
      - exec: $fallback

  # 启动 udp 服务器。
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":5335"

  # 启动 tcp 服务器。
  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":5335"
```
